#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KvasDAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Helpdesk_Kvas")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertEmpleados(Empleados instance);
    partial void UpdateEmpleados(Empleados instance);
    partial void DeleteEmpleados(Empleados instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void InsertGrupos(Grupos instance);
    partial void UpdateGrupos(Grupos instance);
    partial void DeleteGrupos(Grupos instance);
    partial void InsertGruposDetalles(GruposDetalles instance);
    partial void UpdateGruposDetalles(GruposDetalles instance);
    partial void DeleteGruposDetalles(GruposDetalles instance);
    partial void InsertPermisosPorRoles(PermisosPorRoles instance);
    partial void UpdatePermisosPorRoles(PermisosPorRoles instance);
    partial void DeletePermisosPorRoles(PermisosPorRoles instance);
    partial void InsertPersonas(Personas instance);
    partial void UpdatePersonas(Personas instance);
    partial void DeletePersonas(Personas instance);
    #endregion
		
		public dbDataContext() : 
				base(global::KvasDAL.Properties.Settings.Default.Helpdesk_KvasConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Empleados> Empleados
		{
			get
			{
				return this.GetTable<Empleados>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<Grupos> Grupos
		{
			get
			{
				return this.GetTable<Grupos>();
			}
		}
		
		public System.Data.Linq.Table<GruposDetalles> GruposDetalles
		{
			get
			{
				return this.GetTable<GruposDetalles>();
			}
		}
		
		public System.Data.Linq.Table<PermisosPorRoles> PermisosPorRoles
		{
			get
			{
				return this.GetTable<PermisosPorRoles>();
			}
		}
		
		public System.Data.Linq.Table<Personas> Personas
		{
			get
			{
				return this.GetTable<Personas>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarGrupo")]
		public int sp_ActualizarGrupo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdGrupo", DbType="Int")] System.Nullable<int> idGrupo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Titulo", DbType="VarChar(50)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Orden", DbType="Int")] System.Nullable<int> orden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Icono", DbType="VarChar(30)")] string icono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UrlGrupo", DbType="VarChar(50)")] string urlGrupo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idGrupo, titulo, descripcion, orden, icono, urlGrupo, estatus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ListarGrupo")]
		public ISingleResult<sp_ListarGrupoResult> sp_ListarGrupo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ListarGrupoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AgregarGrupo")]
		public int sp_AgregarGrupo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Titulo", DbType="VarChar(50)")] string titulo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Orden", DbType="Int")] System.Nullable<int> orden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Icono", DbType="VarChar(30)")] string icono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UrlGrupo", DbType="VarChar(50)")] string urlGrupo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaRegistro", DbType="DateTime")] System.Nullable<System.DateTime> fechaRegistro)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), titulo, descripcion, orden, icono, urlGrupo, estatus, fechaRegistro);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AgregarUsuario")]
		public int sp_AgregarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreUsuario", DbType="VarChar(30)")] string nombreUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(100)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRole", DbType="Int")] System.Nullable<int> idRole, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPSeguridad", DbType="Int")] System.Nullable<int> idPSeguridad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RespuestaP", DbType="VarChar(50)")] string respuestaP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaRegistro", DbType="DateTime")] System.Nullable<System.DateTime> fechaRegistro)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreUsuario, contrasena, idRole, idPSeguridad, respuestaP, estatus, fechaRegistro);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarGrupo")]
		public int sp_EliminarGrupo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdGrupo", DbType="Int")] System.Nullable<int> idGrupo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idGrupo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ListarDetalles_x_Grupo")]
		public ISingleResult<sp_ListarDetalles_x_GrupoResult> sp_ListarDetalles_x_Grupo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdGrupo", DbType="Int")] System.Nullable<int> idGrupo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idGrupo);
			return ((ISingleResult<sp_ListarDetalles_x_GrupoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleados")]
	public partial class Empleados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPersona;
		
		private int _IdUsuario;
		
		private EntityRef<Usuarios> _Usuarios;
		
		private EntityRef<Personas> _Personas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPersonaChanging(int value);
    partial void OnIdPersonaChanged();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    #endregion
		
		public Empleados()
		{
			this._Usuarios = default(EntityRef<Usuarios>);
			this._Personas = default(EntityRef<Personas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersona", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPersona
		{
			get
			{
				return this._IdPersona;
			}
			set
			{
				if ((this._IdPersona != value))
				{
					if (this._Personas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPersonaChanging(value);
					this.SendPropertyChanging();
					this._IdPersona = value;
					this.SendPropertyChanged("IdPersona");
					this.OnIdPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Empleados", Storage="_Usuarios", ThisKey="IdUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.Empleados.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.Empleados.Add(this);
						this._IdUsuario = value.IdUsuario;
					}
					else
					{
						this._IdUsuario = default(int);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personas_Empleados", Storage="_Personas", ThisKey="IdPersona", OtherKey="IdPersona", IsForeignKey=true)]
		public Personas Personas
		{
			get
			{
				return this._Personas.Entity;
			}
			set
			{
				Personas previousValue = this._Personas.Entity;
				if (((previousValue != value) 
							|| (this._Personas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Personas.Entity = null;
						previousValue.Empleados.Remove(this);
					}
					this._Personas.Entity = value;
					if ((value != null))
					{
						value.Empleados.Add(this);
						this._IdPersona = value.IdPersona;
					}
					else
					{
						this._IdPersona = default(int);
					}
					this.SendPropertyChanged("Personas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUsuario;
		
		private string _NombreUsuario;
		
		private string _Contrasena;
		
		private int _IdRol;
		
		private int _IdPreguntaSeguridad;
		
		private string _RespuestaSeguridad;
		
		private System.Nullable<System.DateTime> _FechaLogin;
		
		private short _ContadorFallido;
		
		private bool _Estatus;
		
		private System.DateTime _FechaRegistro;
		
		private System.Nullable<System.DateTime> _FechaModificacion;
		
		private EntitySet<Empleados> _Empleados;
		
		private EntityRef<GruposDetalles> _GruposDetalles;
		
		private EntityRef<GruposDetalles> _GruposDetalles1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnNombreUsuarioChanging(string value);
    partial void OnNombreUsuarioChanged();
    partial void OnContrasenaChanging(string value);
    partial void OnContrasenaChanged();
    partial void OnIdRolChanging(int value);
    partial void OnIdRolChanged();
    partial void OnIdPreguntaSeguridadChanging(int value);
    partial void OnIdPreguntaSeguridadChanged();
    partial void OnRespuestaSeguridadChanging(string value);
    partial void OnRespuestaSeguridadChanged();
    partial void OnFechaLoginChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaLoginChanged();
    partial void OnContadorFallidoChanging(short value);
    partial void OnContadorFallidoChanged();
    partial void OnEstatusChanging(bool value);
    partial void OnEstatusChanged();
    partial void OnFechaRegistroChanging(System.DateTime value);
    partial void OnFechaRegistroChanged();
    partial void OnFechaModificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaModificacionChanged();
    #endregion
		
		public Usuarios()
		{
			this._Empleados = new EntitySet<Empleados>(new Action<Empleados>(this.attach_Empleados), new Action<Empleados>(this.detach_Empleados));
			this._GruposDetalles = default(EntityRef<GruposDetalles>);
			this._GruposDetalles1 = default(EntityRef<GruposDetalles>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this.OnNombreUsuarioChanging(value);
					this.SendPropertyChanging();
					this._NombreUsuario = value;
					this.SendPropertyChanged("NombreUsuario");
					this.OnNombreUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="Int NOT NULL")]
		public int IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					if (this._GruposDetalles1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdRolChanging(value);
					this.SendPropertyChanging();
					this._IdRol = value;
					this.SendPropertyChanged("IdRol");
					this.OnIdRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPreguntaSeguridad", DbType="Int NOT NULL")]
		public int IdPreguntaSeguridad
		{
			get
			{
				return this._IdPreguntaSeguridad;
			}
			set
			{
				if ((this._IdPreguntaSeguridad != value))
				{
					if (this._GruposDetalles.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPreguntaSeguridadChanging(value);
					this.SendPropertyChanging();
					this._IdPreguntaSeguridad = value;
					this.SendPropertyChanged("IdPreguntaSeguridad");
					this.OnIdPreguntaSeguridadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RespuestaSeguridad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RespuestaSeguridad
		{
			get
			{
				return this._RespuestaSeguridad;
			}
			set
			{
				if ((this._RespuestaSeguridad != value))
				{
					this.OnRespuestaSeguridadChanging(value);
					this.SendPropertyChanging();
					this._RespuestaSeguridad = value;
					this.SendPropertyChanged("RespuestaSeguridad");
					this.OnRespuestaSeguridadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaLogin
		{
			get
			{
				return this._FechaLogin;
			}
			set
			{
				if ((this._FechaLogin != value))
				{
					this.OnFechaLoginChanging(value);
					this.SendPropertyChanging();
					this._FechaLogin = value;
					this.SendPropertyChanged("FechaLogin");
					this.OnFechaLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContadorFallido", DbType="SmallInt NOT NULL")]
		public short ContadorFallido
		{
			get
			{
				return this._ContadorFallido;
			}
			set
			{
				if ((this._ContadorFallido != value))
				{
					this.OnContadorFallidoChanging(value);
					this.SendPropertyChanging();
					this._ContadorFallido = value;
					this.SendPropertyChanged("ContadorFallido");
					this.OnContadorFallidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit NOT NULL")]
		public bool Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this.OnEstatusChanging(value);
					this.SendPropertyChanging();
					this._Estatus = value;
					this.SendPropertyChanged("Estatus");
					this.OnEstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this.OnFechaModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaModificacion = value;
					this.SendPropertyChanged("FechaModificacion");
					this.OnFechaModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_Empleados", Storage="_Empleados", ThisKey="IdUsuario", OtherKey="IdUsuario")]
		public EntitySet<Empleados> Empleados
		{
			get
			{
				return this._Empleados;
			}
			set
			{
				this._Empleados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GruposDetalles_Usuarios", Storage="_GruposDetalles", ThisKey="IdPreguntaSeguridad", OtherKey="IdGrupoDetalle", IsForeignKey=true)]
		public GruposDetalles GruposDetalles
		{
			get
			{
				return this._GruposDetalles.Entity;
			}
			set
			{
				GruposDetalles previousValue = this._GruposDetalles.Entity;
				if (((previousValue != value) 
							|| (this._GruposDetalles.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GruposDetalles.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._GruposDetalles.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._IdPreguntaSeguridad = value.IdGrupoDetalle;
					}
					else
					{
						this._IdPreguntaSeguridad = default(int);
					}
					this.SendPropertyChanged("GruposDetalles");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GruposDetalles_Usuarios1", Storage="_GruposDetalles1", ThisKey="IdRol", OtherKey="IdGrupoDetalle", IsForeignKey=true)]
		public GruposDetalles GruposDetalles1
		{
			get
			{
				return this._GruposDetalles1.Entity;
			}
			set
			{
				GruposDetalles previousValue = this._GruposDetalles1.Entity;
				if (((previousValue != value) 
							|| (this._GruposDetalles1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GruposDetalles1.Entity = null;
						previousValue.Usuarios1.Remove(this);
					}
					this._GruposDetalles1.Entity = value;
					if ((value != null))
					{
						value.Usuarios1.Add(this);
						this._IdRol = value.IdGrupoDetalle;
					}
					else
					{
						this._IdRol = default(int);
					}
					this.SendPropertyChanged("GruposDetalles1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Empleados(Empleados entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_Empleados(Empleados entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Grupos")]
	public partial class Grupos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdGrupo;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private int _Orden;
		
		private string _Icono;
		
		private string _UrlGrupo;
		
		private bool _Estatus;
		
		private System.DateTime _FechaRegistro;
		
		private EntitySet<GruposDetalles> _GruposDetalles;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdGrupoChanging(int value);
    partial void OnIdGrupoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnOrdenChanging(int value);
    partial void OnOrdenChanged();
    partial void OnIconoChanging(string value);
    partial void OnIconoChanged();
    partial void OnUrlGrupoChanging(string value);
    partial void OnUrlGrupoChanged();
    partial void OnEstatusChanging(bool value);
    partial void OnEstatusChanged();
    partial void OnFechaRegistroChanging(System.DateTime value);
    partial void OnFechaRegistroChanged();
    #endregion
		
		public Grupos()
		{
			this._GruposDetalles = new EntitySet<GruposDetalles>(new Action<GruposDetalles>(this.attach_GruposDetalles), new Action<GruposDetalles>(this.detach_GruposDetalles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGrupo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdGrupo
		{
			get
			{
				return this._IdGrupo;
			}
			set
			{
				if ((this._IdGrupo != value))
				{
					this.OnIdGrupoChanging(value);
					this.SendPropertyChanging();
					this._IdGrupo = value;
					this.SendPropertyChanged("IdGrupo");
					this.OnIdGrupoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orden", DbType="Int NOT NULL")]
		public int Orden
		{
			get
			{
				return this._Orden;
			}
			set
			{
				if ((this._Orden != value))
				{
					this.OnOrdenChanging(value);
					this.SendPropertyChanging();
					this._Orden = value;
					this.SendPropertyChanged("Orden");
					this.OnOrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icono", DbType="NVarChar(30)")]
		public string Icono
		{
			get
			{
				return this._Icono;
			}
			set
			{
				if ((this._Icono != value))
				{
					this.OnIconoChanging(value);
					this.SendPropertyChanging();
					this._Icono = value;
					this.SendPropertyChanged("Icono");
					this.OnIconoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlGrupo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UrlGrupo
		{
			get
			{
				return this._UrlGrupo;
			}
			set
			{
				if ((this._UrlGrupo != value))
				{
					this.OnUrlGrupoChanging(value);
					this.SendPropertyChanging();
					this._UrlGrupo = value;
					this.SendPropertyChanged("UrlGrupo");
					this.OnUrlGrupoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit NOT NULL")]
		public bool Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this.OnEstatusChanging(value);
					this.SendPropertyChanging();
					this._Estatus = value;
					this.SendPropertyChanged("Estatus");
					this.OnEstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Grupos_GruposDetalles", Storage="_GruposDetalles", ThisKey="IdGrupo", OtherKey="IdGrupo")]
		public EntitySet<GruposDetalles> GruposDetalles
		{
			get
			{
				return this._GruposDetalles;
			}
			set
			{
				this._GruposDetalles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GruposDetalles(GruposDetalles entity)
		{
			this.SendPropertyChanging();
			entity.Grupos = this;
		}
		
		private void detach_GruposDetalles(GruposDetalles entity)
		{
			this.SendPropertyChanging();
			entity.Grupos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GruposDetalles")]
	public partial class GruposDetalles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdGrupoDetalle;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private int _Orden;
		
		private int _IdGrupo;
		
		private int _IdPadre;
		
		private string _Icono;
		
		private string _UrlDetalle;
		
		private bool _Estatus;
		
		private System.DateTime _FechaRegistro;
		
		private EntitySet<Usuarios> _Usuarios;
		
		private EntitySet<Usuarios> _Usuarios1;
		
		private EntitySet<GruposDetalles> _GruposDetalles2;
		
		private EntitySet<PermisosPorRoles> _PermisosPorRoles;
		
		private EntitySet<PermisosPorRoles> _PermisosPorRoles1;
		
		private EntitySet<Personas> _Personas;
		
		private EntityRef<Grupos> _Grupos;
		
		private EntityRef<GruposDetalles> _GruposDetalles1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdGrupoDetalleChanging(int value);
    partial void OnIdGrupoDetalleChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnOrdenChanging(int value);
    partial void OnOrdenChanged();
    partial void OnIdGrupoChanging(int value);
    partial void OnIdGrupoChanged();
    partial void OnIdPadreChanging(int value);
    partial void OnIdPadreChanged();
    partial void OnIconoChanging(string value);
    partial void OnIconoChanged();
    partial void OnUrlDetalleChanging(string value);
    partial void OnUrlDetalleChanged();
    partial void OnEstatusChanging(bool value);
    partial void OnEstatusChanged();
    partial void OnFechaRegistroChanging(System.DateTime value);
    partial void OnFechaRegistroChanged();
    #endregion
		
		public GruposDetalles()
		{
			this._Usuarios = new EntitySet<Usuarios>(new Action<Usuarios>(this.attach_Usuarios), new Action<Usuarios>(this.detach_Usuarios));
			this._Usuarios1 = new EntitySet<Usuarios>(new Action<Usuarios>(this.attach_Usuarios1), new Action<Usuarios>(this.detach_Usuarios1));
			this._GruposDetalles2 = new EntitySet<GruposDetalles>(new Action<GruposDetalles>(this.attach_GruposDetalles2), new Action<GruposDetalles>(this.detach_GruposDetalles2));
			this._PermisosPorRoles = new EntitySet<PermisosPorRoles>(new Action<PermisosPorRoles>(this.attach_PermisosPorRoles), new Action<PermisosPorRoles>(this.detach_PermisosPorRoles));
			this._PermisosPorRoles1 = new EntitySet<PermisosPorRoles>(new Action<PermisosPorRoles>(this.attach_PermisosPorRoles1), new Action<PermisosPorRoles>(this.detach_PermisosPorRoles1));
			this._Personas = new EntitySet<Personas>(new Action<Personas>(this.attach_Personas), new Action<Personas>(this.detach_Personas));
			this._Grupos = default(EntityRef<Grupos>);
			this._GruposDetalles1 = default(EntityRef<GruposDetalles>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGrupoDetalle", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdGrupoDetalle
		{
			get
			{
				return this._IdGrupoDetalle;
			}
			set
			{
				if ((this._IdGrupoDetalle != value))
				{
					this.OnIdGrupoDetalleChanging(value);
					this.SendPropertyChanging();
					this._IdGrupoDetalle = value;
					this.SendPropertyChanged("IdGrupoDetalle");
					this.OnIdGrupoDetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orden", DbType="Int NOT NULL")]
		public int Orden
		{
			get
			{
				return this._Orden;
			}
			set
			{
				if ((this._Orden != value))
				{
					this.OnOrdenChanging(value);
					this.SendPropertyChanging();
					this._Orden = value;
					this.SendPropertyChanged("Orden");
					this.OnOrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGrupo", DbType="Int NOT NULL")]
		public int IdGrupo
		{
			get
			{
				return this._IdGrupo;
			}
			set
			{
				if ((this._IdGrupo != value))
				{
					if (this._Grupos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdGrupoChanging(value);
					this.SendPropertyChanging();
					this._IdGrupo = value;
					this.SendPropertyChanged("IdGrupo");
					this.OnIdGrupoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPadre", DbType="Int NOT NULL")]
		public int IdPadre
		{
			get
			{
				return this._IdPadre;
			}
			set
			{
				if ((this._IdPadre != value))
				{
					if (this._GruposDetalles1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPadreChanging(value);
					this.SendPropertyChanging();
					this._IdPadre = value;
					this.SendPropertyChanged("IdPadre");
					this.OnIdPadreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icono", DbType="NVarChar(30)")]
		public string Icono
		{
			get
			{
				return this._Icono;
			}
			set
			{
				if ((this._Icono != value))
				{
					this.OnIconoChanging(value);
					this.SendPropertyChanging();
					this._Icono = value;
					this.SendPropertyChanged("Icono");
					this.OnIconoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlDetalle", DbType="VarChar(30)")]
		public string UrlDetalle
		{
			get
			{
				return this._UrlDetalle;
			}
			set
			{
				if ((this._UrlDetalle != value))
				{
					this.OnUrlDetalleChanging(value);
					this.SendPropertyChanging();
					this._UrlDetalle = value;
					this.SendPropertyChanged("UrlDetalle");
					this.OnUrlDetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit NOT NULL")]
		public bool Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this.OnEstatusChanging(value);
					this.SendPropertyChanging();
					this._Estatus = value;
					this.SendPropertyChanged("Estatus");
					this.OnEstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GruposDetalles_Usuarios", Storage="_Usuarios", ThisKey="IdGrupoDetalle", OtherKey="IdPreguntaSeguridad")]
		public EntitySet<Usuarios> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GruposDetalles_Usuarios1", Storage="_Usuarios1", ThisKey="IdGrupoDetalle", OtherKey="IdRol")]
		public EntitySet<Usuarios> Usuarios1
		{
			get
			{
				return this._Usuarios1;
			}
			set
			{
				this._Usuarios1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GruposDetalles_GruposDetalles", Storage="_GruposDetalles2", ThisKey="IdGrupoDetalle", OtherKey="IdPadre")]
		public EntitySet<GruposDetalles> GruposDetalles2
		{
			get
			{
				return this._GruposDetalles2;
			}
			set
			{
				this._GruposDetalles2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GruposDetalles_PermisosPorRoles", Storage="_PermisosPorRoles", ThisKey="IdGrupoDetalle", OtherKey="IdPermiso")]
		public EntitySet<PermisosPorRoles> PermisosPorRoles
		{
			get
			{
				return this._PermisosPorRoles;
			}
			set
			{
				this._PermisosPorRoles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GruposDetalles_PermisosPorRoles1", Storage="_PermisosPorRoles1", ThisKey="IdGrupoDetalle", OtherKey="IdRol")]
		public EntitySet<PermisosPorRoles> PermisosPorRoles1
		{
			get
			{
				return this._PermisosPorRoles1;
			}
			set
			{
				this._PermisosPorRoles1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GruposDetalles_Personas", Storage="_Personas", ThisKey="IdGrupoDetalle", OtherKey="IdTipoPersona")]
		public EntitySet<Personas> Personas
		{
			get
			{
				return this._Personas;
			}
			set
			{
				this._Personas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Grupos_GruposDetalles", Storage="_Grupos", ThisKey="IdGrupo", OtherKey="IdGrupo", IsForeignKey=true)]
		public Grupos Grupos
		{
			get
			{
				return this._Grupos.Entity;
			}
			set
			{
				Grupos previousValue = this._Grupos.Entity;
				if (((previousValue != value) 
							|| (this._Grupos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Grupos.Entity = null;
						previousValue.GruposDetalles.Remove(this);
					}
					this._Grupos.Entity = value;
					if ((value != null))
					{
						value.GruposDetalles.Add(this);
						this._IdGrupo = value.IdGrupo;
					}
					else
					{
						this._IdGrupo = default(int);
					}
					this.SendPropertyChanged("Grupos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GruposDetalles_GruposDetalles", Storage="_GruposDetalles1", ThisKey="IdPadre", OtherKey="IdGrupoDetalle", IsForeignKey=true)]
		public GruposDetalles GruposDetalles1
		{
			get
			{
				return this._GruposDetalles1.Entity;
			}
			set
			{
				GruposDetalles previousValue = this._GruposDetalles1.Entity;
				if (((previousValue != value) 
							|| (this._GruposDetalles1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GruposDetalles1.Entity = null;
						previousValue.GruposDetalles2.Remove(this);
					}
					this._GruposDetalles1.Entity = value;
					if ((value != null))
					{
						value.GruposDetalles2.Add(this);
						this._IdPadre = value.IdGrupoDetalle;
					}
					else
					{
						this._IdPadre = default(int);
					}
					this.SendPropertyChanged("GruposDetalles1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.GruposDetalles = this;
		}
		
		private void detach_Usuarios(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.GruposDetalles = null;
		}
		
		private void attach_Usuarios1(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.GruposDetalles1 = this;
		}
		
		private void detach_Usuarios1(Usuarios entity)
		{
			this.SendPropertyChanging();
			entity.GruposDetalles1 = null;
		}
		
		private void attach_GruposDetalles2(GruposDetalles entity)
		{
			this.SendPropertyChanging();
			entity.GruposDetalles1 = this;
		}
		
		private void detach_GruposDetalles2(GruposDetalles entity)
		{
			this.SendPropertyChanging();
			entity.GruposDetalles1 = null;
		}
		
		private void attach_PermisosPorRoles(PermisosPorRoles entity)
		{
			this.SendPropertyChanging();
			entity.GruposDetalles = this;
		}
		
		private void detach_PermisosPorRoles(PermisosPorRoles entity)
		{
			this.SendPropertyChanging();
			entity.GruposDetalles = null;
		}
		
		private void attach_PermisosPorRoles1(PermisosPorRoles entity)
		{
			this.SendPropertyChanging();
			entity.GruposDetalles1 = this;
		}
		
		private void detach_PermisosPorRoles1(PermisosPorRoles entity)
		{
			this.SendPropertyChanging();
			entity.GruposDetalles1 = null;
		}
		
		private void attach_Personas(Personas entity)
		{
			this.SendPropertyChanging();
			entity.GruposDetalles = this;
		}
		
		private void detach_Personas(Personas entity)
		{
			this.SendPropertyChanging();
			entity.GruposDetalles = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PermisosPorRoles")]
	public partial class PermisosPorRoles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdRol;
		
		private int _IdPermiso;
		
		private EntityRef<GruposDetalles> _GruposDetalles;
		
		private EntityRef<GruposDetalles> _GruposDetalles1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRolChanging(int value);
    partial void OnIdRolChanged();
    partial void OnIdPermisoChanging(int value);
    partial void OnIdPermisoChanged();
    #endregion
		
		public PermisosPorRoles()
		{
			this._GruposDetalles = default(EntityRef<GruposDetalles>);
			this._GruposDetalles1 = default(EntityRef<GruposDetalles>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					if (this._GruposDetalles1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdRolChanging(value);
					this.SendPropertyChanging();
					this._IdRol = value;
					this.SendPropertyChanged("IdRol");
					this.OnIdRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPermiso", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPermiso
		{
			get
			{
				return this._IdPermiso;
			}
			set
			{
				if ((this._IdPermiso != value))
				{
					if (this._GruposDetalles.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPermisoChanging(value);
					this.SendPropertyChanging();
					this._IdPermiso = value;
					this.SendPropertyChanged("IdPermiso");
					this.OnIdPermisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GruposDetalles_PermisosPorRoles", Storage="_GruposDetalles", ThisKey="IdPermiso", OtherKey="IdGrupoDetalle", IsForeignKey=true)]
		public GruposDetalles GruposDetalles
		{
			get
			{
				return this._GruposDetalles.Entity;
			}
			set
			{
				GruposDetalles previousValue = this._GruposDetalles.Entity;
				if (((previousValue != value) 
							|| (this._GruposDetalles.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GruposDetalles.Entity = null;
						previousValue.PermisosPorRoles.Remove(this);
					}
					this._GruposDetalles.Entity = value;
					if ((value != null))
					{
						value.PermisosPorRoles.Add(this);
						this._IdPermiso = value.IdGrupoDetalle;
					}
					else
					{
						this._IdPermiso = default(int);
					}
					this.SendPropertyChanged("GruposDetalles");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GruposDetalles_PermisosPorRoles1", Storage="_GruposDetalles1", ThisKey="IdRol", OtherKey="IdGrupoDetalle", IsForeignKey=true)]
		public GruposDetalles GruposDetalles1
		{
			get
			{
				return this._GruposDetalles1.Entity;
			}
			set
			{
				GruposDetalles previousValue = this._GruposDetalles1.Entity;
				if (((previousValue != value) 
							|| (this._GruposDetalles1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GruposDetalles1.Entity = null;
						previousValue.PermisosPorRoles1.Remove(this);
					}
					this._GruposDetalles1.Entity = value;
					if ((value != null))
					{
						value.PermisosPorRoles1.Add(this);
						this._IdRol = value.IdGrupoDetalle;
					}
					else
					{
						this._IdRol = default(int);
					}
					this.SendPropertyChanged("GruposDetalles1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Personas")]
	public partial class Personas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPersona;
		
		private string _Nombres;
		
		private int _IdTipoPersona;
		
		private string _CiRif;
		
		private string _Direccion;
		
		private string _Telefonos;
		
		private string _Email;
		
		private string _Imagen;
		
		private System.DateTime _FechaRegistro;
		
		private EntitySet<Empleados> _Empleados;
		
		private EntityRef<GruposDetalles> _GruposDetalles;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPersonaChanging(int value);
    partial void OnIdPersonaChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnIdTipoPersonaChanging(int value);
    partial void OnIdTipoPersonaChanged();
    partial void OnCiRifChanging(string value);
    partial void OnCiRifChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonosChanging(string value);
    partial void OnTelefonosChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnImagenChanging(string value);
    partial void OnImagenChanged();
    partial void OnFechaRegistroChanging(System.DateTime value);
    partial void OnFechaRegistroChanged();
    #endregion
		
		public Personas()
		{
			this._Empleados = new EntitySet<Empleados>(new Action<Empleados>(this.attach_Empleados), new Action<Empleados>(this.detach_Empleados));
			this._GruposDetalles = default(EntityRef<GruposDetalles>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersona", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPersona
		{
			get
			{
				return this._IdPersona;
			}
			set
			{
				if ((this._IdPersona != value))
				{
					this.OnIdPersonaChanging(value);
					this.SendPropertyChanging();
					this._IdPersona = value;
					this.SendPropertyChanged("IdPersona");
					this.OnIdPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoPersona", DbType="Int NOT NULL")]
		public int IdTipoPersona
		{
			get
			{
				return this._IdTipoPersona;
			}
			set
			{
				if ((this._IdTipoPersona != value))
				{
					if (this._GruposDetalles.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTipoPersonaChanging(value);
					this.SendPropertyChanging();
					this._IdTipoPersona = value;
					this.SendPropertyChanged("IdTipoPersona");
					this.OnIdTipoPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CiRif", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string CiRif
		{
			get
			{
				return this._CiRif;
			}
			set
			{
				if ((this._CiRif != value))
				{
					this.OnCiRifChanging(value);
					this.SendPropertyChanging();
					this._CiRif = value;
					this.SendPropertyChanged("CiRif");
					this.OnCiRifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefonos", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Telefonos
		{
			get
			{
				return this._Telefonos;
			}
			set
			{
				if ((this._Telefonos != value))
				{
					this.OnTelefonosChanging(value);
					this.SendPropertyChanging();
					this._Telefonos = value;
					this.SendPropertyChanged("Telefonos");
					this.OnTelefonosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(60)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Imagen
		{
			get
			{
				return this._Imagen;
			}
			set
			{
				if ((this._Imagen != value))
				{
					this.OnImagenChanging(value);
					this.SendPropertyChanging();
					this._Imagen = value;
					this.SendPropertyChanged("Imagen");
					this.OnImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personas_Empleados", Storage="_Empleados", ThisKey="IdPersona", OtherKey="IdPersona")]
		public EntitySet<Empleados> Empleados
		{
			get
			{
				return this._Empleados;
			}
			set
			{
				this._Empleados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GruposDetalles_Personas", Storage="_GruposDetalles", ThisKey="IdTipoPersona", OtherKey="IdGrupoDetalle", IsForeignKey=true)]
		public GruposDetalles GruposDetalles
		{
			get
			{
				return this._GruposDetalles.Entity;
			}
			set
			{
				GruposDetalles previousValue = this._GruposDetalles.Entity;
				if (((previousValue != value) 
							|| (this._GruposDetalles.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GruposDetalles.Entity = null;
						previousValue.Personas.Remove(this);
					}
					this._GruposDetalles.Entity = value;
					if ((value != null))
					{
						value.Personas.Add(this);
						this._IdTipoPersona = value.IdGrupoDetalle;
					}
					else
					{
						this._IdTipoPersona = default(int);
					}
					this.SendPropertyChanged("GruposDetalles");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Empleados(Empleados entity)
		{
			this.SendPropertyChanging();
			entity.Personas = this;
		}
		
		private void detach_Empleados(Empleados entity)
		{
			this.SendPropertyChanging();
			entity.Personas = null;
		}
	}
	
	public partial class sp_ListarGrupoResult
	{
		
		private int _IdGrupo;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private int _Orden;
		
		private string _Icono;
		
		private string _UrlGrupo;
		
		private bool _Estatus;
		
		private System.DateTime _FechaRegistro;
		
		public sp_ListarGrupoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGrupo", DbType="Int NOT NULL")]
		public int IdGrupo
		{
			get
			{
				return this._IdGrupo;
			}
			set
			{
				if ((this._IdGrupo != value))
				{
					this._IdGrupo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orden", DbType="Int NOT NULL")]
		public int Orden
		{
			get
			{
				return this._Orden;
			}
			set
			{
				if ((this._Orden != value))
				{
					this._Orden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icono", DbType="NVarChar(30)")]
		public string Icono
		{
			get
			{
				return this._Icono;
			}
			set
			{
				if ((this._Icono != value))
				{
					this._Icono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlGrupo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UrlGrupo
		{
			get
			{
				return this._UrlGrupo;
			}
			set
			{
				if ((this._UrlGrupo != value))
				{
					this._UrlGrupo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit NOT NULL")]
		public bool Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this._FechaRegistro = value;
				}
			}
		}
	}
	
	public partial class sp_ListarDetalles_x_GrupoResult
	{
		
		private int _IdGrupoDetalle;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private int _Orden;
		
		private string _Grupo;
		
		private int _Categoria;
		
		private string _Icono;
		
		private string _UrlDetalle;
		
		private bool _Estatus;
		
		private System.DateTime _FechaRegistro;
		
		public sp_ListarDetalles_x_GrupoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGrupoDetalle", DbType="Int NOT NULL")]
		public int IdGrupoDetalle
		{
			get
			{
				return this._IdGrupoDetalle;
			}
			set
			{
				if ((this._IdGrupoDetalle != value))
				{
					this._IdGrupoDetalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orden", DbType="Int NOT NULL")]
		public int Orden
		{
			get
			{
				return this._Orden;
			}
			set
			{
				if ((this._Orden != value))
				{
					this._Orden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grupo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Grupo
		{
			get
			{
				return this._Grupo;
			}
			set
			{
				if ((this._Grupo != value))
				{
					this._Grupo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="Int NOT NULL")]
		public int Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icono", DbType="NVarChar(30)")]
		public string Icono
		{
			get
			{
				return this._Icono;
			}
			set
			{
				if ((this._Icono != value))
				{
					this._Icono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlDetalle", DbType="VarChar(30)")]
		public string UrlDetalle
		{
			get
			{
				return this._UrlDetalle;
			}
			set
			{
				if ((this._UrlDetalle != value))
				{
					this._UrlDetalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit NOT NULL")]
		public bool Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this._FechaRegistro = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
