<?xml version="1.0" encoding="utf-8"?><Database Name="Helpdesk_Kvas" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Helpdesk_Kvas;Integrated Security=True" SettingsObjectName="KvasDAL.Properties.Settings" SettingsPropertyName="Helpdesk_KvasConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Grupos" Member="Grupos">
    <Type Name="Grupos">
      <Column Name="IdGrupo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Orden" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Icono" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UrlGrupo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Grupos_GruposDetalles" Member="GruposDetalles" ThisKey="IdGrupo" OtherKey="IdGrupo" Type="GruposDetalles" />
    </Type>
  </Table>
  <Table Name="dbo.GruposDetalles" Member="GruposDetalles">
    <Type Name="GruposDetalles">
      <Column Name="IdGrupoDetalle" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Orden" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdGrupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdPadre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Icono" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UrlDetalle" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="GruposDetalles_GruposDetalles" Member="GruposDetalles2" ThisKey="IdGrupoDetalle" OtherKey="IdPadre" Type="GruposDetalles" />
      <Association Name="GruposDetalles_Personas" Member="Personas" ThisKey="IdGrupoDetalle" OtherKey="IdTipoPersona" Type="Personas" />
      <Association Name="GruposDetalles_PSDetalles" Member="PSDetalles" ThisKey="IdGrupoDetalle" OtherKey="IdFabricante" Type="PSDetalles" />
      <Association Name="GruposDetalles_PSDetalles1" Member="PSDetalles1" ThisKey="IdGrupoDetalle" OtherKey="IdProducto" Type="PSDetalles" Cardinality="One" />
      <Association Name="GruposDetalles_PSDetalles2" Member="PSDetalles2" ThisKey="IdGrupoDetalle" OtherKey="IdUnidad" Type="PSDetalles" />
      <Association Name="GruposDetalles_Usuarios" Member="Usuarios" ThisKey="IdGrupoDetalle" OtherKey="IdPreguntaSeguridad" Type="Usuarios" />
      <Association Name="GruposDetalles_UsuariosRoles" Member="UsuariosRoles" ThisKey="IdGrupoDetalle" OtherKey="IdRoles" Type="UsuariosRoles" />
      <Association Name="Grupos_GruposDetalles" Member="Grupos" ThisKey="IdGrupo" OtherKey="IdGrupo" Type="Grupos" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="GruposDetalles_GruposDetalles" Member="GruposDetalles1" ThisKey="IdPadre" OtherKey="IdGrupoDetalle" Type="GruposDetalles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Personas" Member="Personas">
    <Type Name="Personas">
      <Column Name="IdPersona" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoPersona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CiRif" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="GruposDetalles_Personas" Member="GruposDetalles" ThisKey="IdTipoPersona" OtherKey="IdGrupoDetalle" Type="GruposDetalles" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Personas" Member="vw_Personas">
    <Type Name="vw_Personas">
      <Column Name="IdPersona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cedula" Type="System.String" DbType="VarChar(61) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PSDetalles" Member="PSDetalles">
    <Type Name="PSDetalles">
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Sku" Type="System.String" DbType="VarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="IdFabricante" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdUnidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Stock_Min" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrecioCompra" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="Garantia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PSDetalles_SerialesProductos" Member="SerialesProductos" ThisKey="IdProducto" OtherKey="IdProducto" Type="SerialesProductos" />
      <Association Name="GruposDetalles_PSDetalles" Member="GruposDetalles" ThisKey="IdFabricante" OtherKey="IdGrupoDetalle" Type="GruposDetalles" IsForeignKey="true" />
      <Association Name="GruposDetalles_PSDetalles1" Member="GruposDetalles1" ThisKey="IdProducto" OtherKey="IdGrupoDetalle" Type="GruposDetalles" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="GruposDetalles_PSDetalles2" Member="GruposDetalles2" ThisKey="IdUnidad" OtherKey="IdGrupoDetalle" Type="GruposDetalles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SerialesProductos" Member="SerialesProductos">
    <Type Name="SerialesProductos">
      <Column Name="IdSerial" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Serial" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="PSDetalles_SerialesProductos" Member="PSDetalles" ThisKey="IdProducto" OtherKey="IdProducto" Type="PSDetalles" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NombreUsuario" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Contrasena" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IdEmail" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="IdPreguntaSeguridad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RespuestaSeguridad" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="FechaLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ContadorFallido" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaModificacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Usuarios_UsuariosRoles" Member="UsuariosRoles" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="UsuariosRoles" />
      <Association Name="GruposDetalles_Usuarios" Member="GruposDetalles" ThisKey="IdPreguntaSeguridad" OtherKey="IdGrupoDetalle" Type="GruposDetalles" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsuariosRoles" Member="UsuariosRoles">
    <Type Name="UsuariosRoles">
      <Column Name="IdUserRoles" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdRoles" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GruposDetalles_UsuariosRoles" Member="GruposDetalles" ThisKey="IdRoles" OtherKey="IdGrupoDetalle" Type="GruposDetalles" IsForeignKey="true" />
      <Association Name="Usuarios_UsuariosRoles" Member="Usuarios" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_ActualizarGrupo" Method="sp_ActualizarGrupo">
    <Parameter Name="IdGrupo" Parameter="idGrupo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Orden" Parameter="orden" Type="System.Int32" DbType="Int" />
    <Parameter Name="Icono" Parameter="icono" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="UrlGrupo" Parameter="urlGrupo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_OperacionesInventarioProducto" Method="sp_OperacionesInventarioProducto">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Operador" Parameter="operador" Type="System.Int32" DbType="Int" />
    <Parameter Name="Stock" Parameter="stock" Type="System.Int32" DbType="Int" />
    <Parameter Name="PrecioCompra" Parameter="precioCompra" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="PrecioVenta" Parameter="precioVenta" Type="System.Decimal" DbType="Decimal(8,2)" />
    <ElementType Name="sp_OperacionesInventarioProductoResult">
      <Column Name="errNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="errSeverity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="errState" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="errProcedure" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="errLine" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="errMessage" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ActualizarGrupoDetalle" Method="sp_ActualizarGrupoDetalle">
    <Parameter Name="IdGrupoDetalle" Parameter="idGrupoDetalle" Type="System.Int32" DbType="Int" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Orden" Parameter="orden" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdGrupo" Parameter="idGrupo" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdPadre" Parameter="idPadre" Type="System.Int32" DbType="Int" />
    <Parameter Name="Icono" Parameter="icono" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="UrlDetalle" Parameter="urlDetalle" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ActualizarPersonas" Method="sp_ActualizarPersonas">
    <Parameter Name="IdPersona" Parameter="idPersona" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombres" Parameter="nombres" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdTipoPersona" Parameter="idTipoPersona" Type="System.Int32" DbType="Int" />
    <Parameter Name="CiRif" Parameter="ciRif" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Telefonos" Parameter="telefonos" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(60)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ActualizarPersonasSimple" Method="sp_ActualizarPersonasSimple">
    <Parameter Name="IdPersona" Parameter="idPersona" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombres" Parameter="nombres" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Telefonos" Parameter="telefonos" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(60)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ActualizarProducto" Method="sp_ActualizarProducto">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Orden" Parameter="orden" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdGrupo" Parameter="idGrupo" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdPadre" Parameter="idPadre" Type="System.Int32" DbType="Int" />
    <Parameter Name="Icono" Parameter="icono" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="UrlDetalle" Parameter="urlDetalle" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Sku" Parameter="sku" Type="System.String" DbType="VarChar(24)" />
    <Parameter Name="IdFabricante" Parameter="idFabricante" Type="System.Int32" DbType="Int" />
    <Parameter Name="Stock" Parameter="stock" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUnidad" Parameter="idUnidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="StockMin" Parameter="stockMin" Type="System.Int32" DbType="Int" />
    <Parameter Name="PrecioCompra" Parameter="precioCompra" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="PrecioVenta" Parameter="precioVenta" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="Garantia" Parameter="garantia" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ActualizarProductoResult">
      <Column Name="errNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="errSeverity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="errState" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="errProcedure" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="errLine" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="errMessage" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_AgregarGrupo" Method="sp_AgregarGrupo">
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Orden" Parameter="orden" Type="System.Int32" DbType="Int" />
    <Parameter Name="Icono" Parameter="icono" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="UrlGrupo" Parameter="urlGrupo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FechaRegistro" Parameter="fechaRegistro" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AgregarGrupoDetalle" Method="sp_AgregarGrupoDetalle">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Orden" Parameter="orden" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdGrupo" Parameter="idGrupo" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdPadre" Parameter="idPadre" Type="System.Int32" DbType="Int" />
    <Parameter Name="Icono" Parameter="icono" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="UrlDetalle" Parameter="urlDetalle" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FechaRegistro" Parameter="fechaRegistro" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AgregarPersonas" Method="sp_AgregarPersonas">
    <Parameter Name="Nombres" Parameter="nombres" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdTipoPersona" Parameter="idTipoPersona" Type="System.Int32" DbType="Int" />
    <Parameter Name="CiRif" Parameter="ciRif" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Telefonos" Parameter="telefonos" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="FechaRegistro" Parameter="fechaRegistro" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AgregarProducto" Method="sp_AgregarProducto">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Orden" Parameter="orden" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdGrupo" Parameter="idGrupo" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdPadre" Parameter="idPadre" Type="System.Int32" DbType="Int" />
    <Parameter Name="Icono" Parameter="icono" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="UrlDetalle" Parameter="urlDetalle" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FechaRegistro" Parameter="fechaRegistro" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Sku" Parameter="sku" Type="System.String" DbType="VarChar(24)" />
    <Parameter Name="IdFabricante" Parameter="idFabricante" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdEquipo" Parameter="idEquipo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Stock" Parameter="stock" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUnidad" Parameter="idUnidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="StockMin" Parameter="stockMin" Type="System.Int32" DbType="Int" />
    <Parameter Name="PrecioCompra" Parameter="precioCompra" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="PrecioVenta" Parameter="precioVenta" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="Garantia" Parameter="garantia" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_AgregarProductoResult">
      <Column Name="errNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="errSeverity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="errState" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="errProcedure" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="errLine" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="errMessage" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_BuscarProducto" Method="sp_BuscarProducto">
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_BuscarProductoResult">
      <Column Name="IdProducto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sku" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="Titulo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdGrupo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Grupo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdPadre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Padre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Icono" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UrlDetalle" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdFabricante" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabricante" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Stock_Min" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdUnidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Garantia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrecioCompra" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_EliminarGrupo" Method="sp_EliminarGrupo">
    <Parameter Name="IdGrupo" Parameter="idGrupo" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarGrupoDetalle" Method="sp_EliminarGrupoDetalle">
    <Parameter Name="IdGrupoDetalle" Parameter="idGrupoDetalle" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarPersonas" Method="sp_EliminarPersonas">
    <Parameter Name="IdPersona" Parameter="idPersona" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarProducto" Method="sp_EliminarProducto">
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ListarDetalles_x_Grupo" Method="sp_ListarDetalles_x_Grupo">
    <Parameter Name="IdGrupo" Parameter="idGrupo" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ListarDetalles_x_GrupoResult">
      <Column Name="IdGrupoDetalle" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Icono" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UrlDetalle" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ListarGrupo" Method="sp_ListarGrupo">
    <ElementType Name="sp_ListarGrupoResult">
      <Column Name="IdGrupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Orden" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Icono" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UrlGrupo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ListarGrupoDetalle" Method="sp_ListarGrupoDetalle">
    <ElementType Name="sp_ListarGrupoDetalleResult">
      <Column Name="IdGrupoDetalle" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Orden" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdGrupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdPadre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Icono" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UrlDetalle" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ListarPersonas" Method="sp_ListarPersonas">
    <ElementType Name="sp_ListarPersonasResult">
      <Column Name="IdPersona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoPersona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CiRif" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ListarProducto" Method="sp_ListarProducto">
    <ElementType Name="sp_ListarProductoResult">
      <Column Name="IdProducto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sku" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdGrupo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Grupo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdPadre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Padre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Icono" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UrlDetalle" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdFabricante" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabricante" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Stock_Min" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdUnidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Unidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Garantia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrecioCompra" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_AgregarUsuario" Method="sp_AgregarUsuario">
    <Parameter Name="NombreUsuario" Parameter="nombreUsuario" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Contrasena" Parameter="contrasena" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="IdPregunta" Parameter="idPregunta" Type="System.Int32" DbType="Int" />
    <Parameter Name="Respuesta" Parameter="respuesta" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Avatar" Parameter="avatar" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FechaRegistro" Parameter="fechaRegistro" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IdRole" Parameter="idRole" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>